### ISSUE TITLE
ebook에서 팝업 콘텐츠를 2개 이상 띄웠을 때 이전에 띄운 팝업창이 닫히지 않음

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#1]
- 2개 중 1번째로 띄운 팝업 종료 불가
 - 3개 중 1, 2번째로 띄운 팝업 종료 불가

-> 각 팝업을 종료하고 할당된 페이지로 이동해야 함.

**Comment by vulcan9** [comment]
0.2.xx버전이면  테스트 이상 없는 것으로 나타남니다. close, message 를 등록해서 사용중이라면 이부분에서 스크립트 오류가 있는지 확인하시기 바랍니다. 
close 이벤트에서 등록한 핸들러에서 스크립트 오류가 나면 종료 스크립트 명령까지 도달하지 못합니다. 이부분은 오류가 나더라도 무시하고 창을 닫는 것으로 차후 수정할 예정입니다. (#3)

**Comment by vulcan9** [comment]
이슈 옮기고 (#3) 이 내용은 닫겠습니다. 문제가 계속된다면 새로운 이슈를 열고 좀더 자세한 내용으로 등록하세요
