### ISSUE TITLE
html이 모두 로딩되기 전에 이 페이지에 클릭을 여러번 하게 되면 간헐적으로 에러얼럿 표시됨.

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#15]
![image](https://cloud.githubusercontent.com/assets/20292746/20051300/b155c940-a511-11e6-854f-fbd75f9dc472.png)
내부 제보(현상 재현은 쉽지 않다고 함)
참고 부탁드립니다.

**Comment by vulcan9** [comment]
**0.3.89** 버전(이상)에서 처리(구현) 되었습니다.
