### ISSUE TITLE
플래시 팝업 열고 닫을 때 오류

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji-Binder#19]
확인되는 오류를 아래에 이어서 쓰겠습니다.

**Comment by onlyeye26** [comment]
1. 팝업을 여러번 빠르게 열고 닫을 때 어느 순간 팝업에 'BLANK'가 뜰 때가 있음.

**Comment by onlyeye26** [comment]
1.팝업을 여러번 빠르게 열고 닫을 때 어느 순간 팝업에 'BLANK'가 뜰 때가 있음.

**Comment by Soarts** [comment]
![-](https://cloud.githubusercontent.com/assets/20292746/20590100/66900bae-b264-11e6-87cf-9ad4d11f5558.jpg)

고객사에서 같은 제보가 왔습니다.(11.24)
한번 발생하고 나면 빈도가 늘어나는 것 같다고 합니다.

**Comment by vulcan9** [comment]
처리중입니다.

**Comment by vulcan9** [comment]
**0.4.148** 버전(이상)에서 처리(구현) 되었습니다.
확인 후 이슈 닫아주시기 바랍니다.

**Comment by Soarts** [comment]
이 현상은 #21 이슈 해결 이후에 더이상 발생하지 않습니다.
