### ISSUE TITLE
팝업콘텐츠를 띄운 상태에서 ebook을 종료하면 팝업창은 종료되지 않음

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#2]
수동으로 종료하려 해도 종료 안됨.

**Comment by vulcan9** [comment]
#1 번과 같은 증상인것 같네요. #3번 확인 바랍니다.
아니라면 재연 가능하도록 좀더 자세한 내용이 필요하네요

**Comment by vulcan9** [comment]
별다른 이슈 제기가 없어 ( #3 )번 이슈와 같은걸로 알겠습니다.
진행 상황은 #3 에서 확인하세요.
이 이슈는 닫겠습니다.
