### ISSUE TITLE
팝업 열고 닫기를 반복하면 백그라운드 프로세스(nwjs)의 메모리 사용량이 점점 늘어나는 이슈

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#20]
1. 팝업을 열고 닫기를 반복하면, 백그라운드 프로세스 nwjs 중 하나의 메모리 사용량이 빠르게 늘어남.

[팝업을 처음 열 때]
![01](https://cloud.githubusercontent.com/assets/20292746/20552653/62ea02a4-b190-11e6-9bf3-488f34380fd6.JPG)

[팝업을 30~40개 정도 연속해서 열었을 때]
![02](https://cloud.githubusercontent.com/assets/20292746/20552658/74a86684-b190-11e6-85b6-69bfc0406d00.JPG)

[팝업을 60~70개 연속해서 열었을 때]
![04](https://cloud.githubusercontent.com/assets/20292746/20552666/81649dd4-b190-11e6-8ba6-e37a099aac92.JPG)

[프로그램의 동작이 느려지기 시작함]
![03](https://cloud.githubusercontent.com/assets/20292746/20552669/86f5473a-b190-11e6-8f44-4d3dd5b6d7da.JPG)

2. 기존 팝업을 열고 닫고 하는 것보다, 계속해서 새로운 팝업을 열 때 메모리 사용량이 더 빨리 늘어남.

3. 메모리 사용량이 대략 1GB를 넘어가는 시점에서 프로그램이 강종 됨.

4. 이 시점에서 강종되기 전 이런 에러가 뜨기도 함(고객사 제보)
![default](https://cloud.githubusercontent.com/assets/20292746/20552689/cd96fad0-b190-11e6-9ac3-963f806f8cdd.jpg)

5. 테스트 컨텐츠 : 미래엔 과학
 - 이 컨텐츠는 ui.html을 사용하지 않는 단일 팝업 형태임. 고객사에서 테스트한 컨텐츠는 ui.html을 사용함. 체감상 더 빠르게 메모리 사용량이 누적되는 것 같습니다.

**Comment by vulcan9** [comment]
단위 테스트 결과 nwJS 버그로 확인되었습니다.
(브라우져 --mixedContext 옵션이 해당 문제에 영향을 줌)
해당 옵션을 제거했을 경우 상당한 양의 코드 리팩토링과 테스트가 필요할것 같습니다.

**Comment by vulcan9** [comment]
nwJS 이슈 제기 내용
---------------------------------------
<https://github.com/nwjs/nw.js>

Window 창을 열고 닫기를 반복하면 메모리 사용량이 지속적으로 늘어납니다.
`chromium-args : --mixed-context` 라고 설정한 경우에 이런 현상이 발생하고, `global.gc() ` 코드를 실행해도 누적된 memory 변화가 없습니다.
`--mixed-context` 옵션을 제거하고 테스트한 경우에는 정상적으로 memory가 해지됩니다.

테스트 코드입니다.
package.json
```
"main": "index.html",
"js-flags": "--expose-gc",
"chromium-args": "--mixed-context",
```
HTML : 
```
<button onclick="window.open('./blank.html', '_blank')">window open</button>
<button onclick="window.open('./index.html', '_self')">reload</button>
```

테스트 환경 :
```
chromium : "54.0.2840.71"
nw : "0.18.2"
nw-commit-id : "a820695-68f77db-ae7e389-2021126"
OS : Windows7, Windows10 32bit
```

버그인가요? 아니면 잘못 사용하고 있는 건가요?

**Comment by Soarts** [comment]
nwjs github에 하기 내용 업로드 되었습니다.
https://github.com/nwjs/nw.js/issues/5504

reply가 하나 달렸습니다.
rogerwang 
Thanks for reporting. Could you please provide the full package.json and index.html?

**Comment by Soarts** [comment]
jikji.binder.demo(16.11.28) 단위 테스트 결과 현상 발생하고 있지 않습니다.

**Comment by vulcan9** [comment]
**0.4.148** 버전(이상)에서 처리(구현) 되었습니다.
