### ISSUE TITLE
특정 콘텐츠에서 팝업 플래시를 띄우고 로딩 중에 닫으면 오류 발생

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#21]
1. 일반적인 현상은 아닌 듯 하고 특정 콘텐츠에서만 발생하는 것으로 판단됨.

2. ebook에서 링크한 팝업 콘텐츠(플래시)를 띄우고 전부 불러와지기 전에 닫으면 발생하는 오류인 것은 이전과 동일함.

3. 특이한 점은 이 콘텐츠는 팝업 콘텐츠(플래시)를 부를 때 하나의 플래시를 부르는게 아니고 
   본 내용 플래시가 뜨기 전에 로딩바가 포함된  플래시를 하나 더, 먼저 실행하는 것 같음.
[팝업 플래시 관련한 swf 파일이 3개 존재함.]
![image](https://cloud.githubusercontent.com/assets/20292746/20583341/5680bbf6-b22c-11e6-8d39-247224c6954b.png)

4. 이 본 내용 플래시가 뜨기 전에, 로딩바 플래시가 뜰 때 닫을 때만 오류가 발생함.
    [오류 메시지]
![image](https://cloud.githubusercontent.com/assets/20292746/20583364/82762426-b22c-11e6-92fd-bff7fa2e9c4e.png)

    
5. 이 메시지 표시를 콘텐츠에서 수정할 수 있다면 콘텐츠에서 수정하면 될 듯 하나, 혹시 에러메시지에서 표시되는 api2/swf.js 혹은 api/listener.js 에서 수정될 부분은 없는지 확인 부탁드립니다.

6. 오류 메시지가 떠도 이후 기능상 문제되는 것은 없어, 단순히 에러메시지 표시만 안되는 방향으로 검토해볼 수 있지 않을까 싶습니다.

**Comment by Soarts** [comment]
이 이슈를 확인하시는 시점에 요청해주시면 해당 콘텐츠 전달해드리겠습니다.(용량이 크고 보안 유지가 필요한 콘텐츠입니다.)

**Comment by vulcan9** [comment]
에러 메세지에 나타나는 frameWeb.html에서 호출하는 toSWF 메서드에서 에러를 발생시키고 있네요
예제코드를 그대로 복사 붙여넣기한것 같습니다.
해당코드 삭제하면 정상동작할것으로 예상됩니다.
다음 40~50라인을 모두 삭제하세요 . 테스트용 코드입니다.

```
// JS -> AS 호출 테스트
function onSwfCreated(){
	var result = loader.toSWF('function_in_flash', '# JS 로부터 전달된 값');
	alert("onswfCreated result =>"+ result);
	//console.log('플래시 함수 실행 결과 : ', result);
}

// 자신의 창에 전달된 메세지를 받습니다.
jj.event.addListener('message', function handler(receiveData, sendingWindow){
	// receiveData == '전달 데이터'
	alert('message : ' + JSON.stringify(receiveData));
});
```

**Comment by Soarts** [comment]
상기 내용대로 수정하니, 기존처럼 로딩바가 돌지 않고 
이번에는 아래와 같은 오류가 뜹니다.
![image](https://cloud.githubusercontent.com/assets/20292746/20611722/fb841b9a-b2f2-11e6-94eb-1500bd44672a.png)

**Comment by vulcan9** [comment]
onSwfCreated 함수를 삭제했으므로 이를 호출하는 부분도 수정합니다.
```
loader.create(contentURL, config, flashVars, onSwfCreated);
```
위 코드(33 라인)를 다음과 같이  수정합니다.
```
loader.create(contentURL, config, flashVars);
```

**Comment by Soarts** [comment]
![image](https://cloud.githubusercontent.com/assets/20292746/20611836/074946e2-b2f5-11e6-88ff-825dd1bca612.png)

그 부분 수정하니 다시 이런 오류가 표시됩니다.
처음 오류하고 비슷해보이네요

**Comment by Soarts** [comment]
클라이언트에 원 개발사를 통한 컨텐츠 수정 검토 요청하였습니다.

**Comment by Soarts** [comment]
jikji.binder.demo(16.11.28) 오늘 버전에서는 약간 다른 에러가 표시되네요.
![03](https://cloud.githubusercontent.com/assets/20292746/20666643/9b999e9a-b5a8-11e6-98ae-920dbb5f3291.JPG)

동일한 오류같아 보이는데 맞는지요?

**Comment by vulcan9** [comment]
같은 오류같습니다. 소스가 달라 에러 라인 표기만 바뀐거 같습니다.

**Comment by vulcan9** [comment]
html에 삽입된 frameWeb.swf 에서 frame.swf를 로드하는 경우...
**frameWeb.swf 로드 후JS 연결 설정**
```
var loader = window.jj.newSWF();
loader.create(contentURL, config, flashVars, onSwfCreated);
// JS -> AS 호출 테스트
var flashLoaded = false;
function onSwfCreated(){
   // 연결 설정됨 (swf에 연결 드가 정상 작성된 경우)
    flashLoaded = true;
}
```
SWF 생성이 완료된 후 통신할 수 있고, 통신을 위한 AS 코드가 frameWeb.swf에 작성되어 있어야 합니다.
```
jj.event.addListener('close', function(closeData, openerWin){
    if(!flashLoaded){
        alert('정상적으로 연결되지 않음');
        return;
    }
    // 플래시에서 현재 페이지 받아오기
    var currentPage = parseInt(loader.toSWF('currentPage'))-7;
    ....
});
```
위 코드에서 loader.toSWF 메서드 호출시 에러가 발생합니다.
flashLoaded 값을 체크해보면 항상 false값이 나타납니다.
frameWeb.swf 에 연동을 위한 AS 코드가 제대로 작성되지 않은것 같습니다.

**Comment by vulcan9** [comment]
**0.4.151** 버전(이상)에서 위 문제가 발생하는 경우 
"SWF 객체와 통신이 설정되지 않았습니다." 라는
alert창을 띄움니다.

**Comment by Soarts** [comment]
확인했습니다.
