### ISSUE TITLE
Jik-ji Binder 실행시, 하단 작업 표시줄에서 우클릭시 나타나는 문구 변경 가능 여부 문의

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#22]
![default](https://cloud.githubusercontent.com/assets/20292746/20611777/0d6c7798-b2f4-11e6-8ecd-6856a696bb2e.jpg)

고객사 요청으로 문의드립니다.

* 작업 표시줄에서 마우스 over시 나타나는 문구를 변경 가능한지 문의드립니다.

* 클라이언트는  Jik-ji-Binder.cdbook이 빠지고 "2015tee_30y.." 이와 같이 app-id만 노출되기를 원함.

**Comment by vulcan9** [comment]
변경 가능합니다.
작업 표시중에 나타나는 문구는 다음 우선순위로 표기됩니다.

1. html의 title 태그 내용
2. window 타이틀 속성에 적용된 값
3. app 이름으로 설정된 값

1번의 방법으로 사용자가 설정 가능하고, 2, 3번은 App에서 수정해야합니다.

**Comment by Soarts** [comment]
고객사에서 다시 얘기를 들어보니, 롤오버시가 아니고 우클릭시 나오는 부분이라고 합니다.
제가 win10에서 테스트했을 때도 이렇게 나오네요.
![default](https://cloud.githubusercontent.com/assets/20292746/20615323/f5b603a8-b31b-11e6-8d29-3547570ad07d.png)

이것도 컨트롤이 가능한지요?

**Comment by Soarts** [comment]
변경 가능 여부 확인하였고
Jik-ji-Binder.cdbook이 빠지고 "2015tee_30y.." 이와 같이 app-id만 표시되도록 수정 요청 드립니다.

**Comment by vulcan9** [comment]
처리중입니다.

**Comment by vulcan9** [comment]
**0.4.148** 버전(이상)에서 처리(구현) 되었습니다.
확인 후 이슈 닫아주시기 바랍니다.

**Comment by Soarts** [comment]
확인 완료
