### ISSUE TITLE
교사용cd 테스트 중 개발자용 화면 표시됨.

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#23]
![img_6154](https://cloud.githubusercontent.com/assets/20292746/20616299/9c9b3c58-b324-11e6-9bc0-5e98ea23a3a1.JPG)

상단 화면이 나오지 않도록 처리 필요합니다.

**Comment by vulcan9** [comment]
처리중입니다.

**Comment by vulcan9** [comment]
**0.4.148** 버전(이상)에서 처리(구현) 되었습니다.
