### ISSUE TITLE
Jik-ji Binder로 실행되는 콘텐츠를 웹에서 서비스하기 위한 방안 논의

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#26]
<샘플>
'비상'에 보여준 웹용 ebook 샘플
http://175.126.167.133/~dns/visang/viewer/index.html
 - ebook page 5로 가시면 팝업으로 웹페이지 열리는 것 확인 가능
 - ebook을 jik-ji 저작도구로 작업

<br><br>

<논의할 사항>
1. main을 웹으로 띄웠을 때 ebook을 열기 위한 방법(현재 Binder의 jj.link.ebook을 사용하고 있음)
2. ebook을 웹으로 띄웠을 때 popup을 웹페이지로 표시하기 위한 방법(현재 Binder의 jj.link.html을 사용하고 있음)
3. index.html이 수정되어야 한다면 어떻게 수정되어야 하는가.(플래시 콘텐츠, html 콘텐츠)
4. 상기 기능을 웹에서 보여주기 위하여 콘텐츠의 수정한다면 수정 작업은 어떤 것들이 필요한가.
5. 상기 기능을 웹에서 보여주기 위하여 콘텐츠를 수정한다면 이 작업을 최소화할 방법이 있는가.

6. 몇가지 검토가 끝나면 Jik-ji Binder와 함께 제공하던 샘플 콘텐츠(영어, 일본어)를 웹버전을 샘플로 만들어보고자 합니다.
<br><br>
개발자 의견을 남겨주시면, 이에 따라 추진해보도록 하겠습니다.

**Comment by Soarts** [comment]
진행 상황 문의드립니다~

**Comment by Soarts** [comment]
[2017.1.26] Jik-ji Binder Web버전 테스트하였습니다.

우선 샘플 html 콘텐츠에 대한 테스트는 완료되었습니다.(메인->ebook->팝업 실행 확인)

**플래시 콘텐츠**는 별도의 콘텐츠 수정(index.html 등)이 필요한 것으로 알고 있습니다.
index.html 외에 swf 파일도 수정이 필요한지, 필요하다면 이에 대한 샘플도 필요할 것 같습니다.
검토 부탁드립니다.

**Comment by vulcan9** [comment]
**0.4.192** 버전(이상)에서 플래시 버전 샘플 추가하여 배포되었습니다.
플래시 버전에서 swf 파일은 수정하지 않아도 됩니다.
자세한 사항은 API 문서에서 확인 바랍니다.

**Comment by Soarts** [comment]
두가지 이슈 확인 요청 드립니다.

1. cross browsing
 - ie, edge, firefox 브라우저에서 ebook - jj.link.html api를 통한 팝업창을 띄울 때, 엉뚱한 경로를 불러서 404에러가 발생하는 케이스가 있습니다.
 - test url : http://175.126.167.133/~dns/jjb_web_test/resource/index.html

2. 통권 ebook 실행시
 - 통권 ebook 실행시 통권내 epub 폴더 하위에 있는 OPS 폴더가 대문자이면 정상 동작 하지 않고 소문자여야지만 정상적으로 ebook 실행이 되는 현상이 있습니다.
 - jik-ji 저작도구에서 epub 출판시 OPS(대문자) 출판되므로 확인이 필요한 부분입니다.

**Comment by vulcan9** [comment]
1. cross browsing
 > ie, edge, firefox 브라우저에서 ebook - jj.link.html api를 통한 팝업창을 띄울 때, 엉뚱한 경로를 불러서 404에러가 발생하는 케이스가 있습니다.
- 수정 예정입니다.

2. 통권 ebook 실행시
 > 통권 ebook 실행시 통권내 epub 폴더 하위에 있는 OPS 폴더가 대문자이면 정상 동작 하지 않고 소문자여야지만 정상적으로 ebook 실행이 되는 현상이 있습니다.
- OPS 경로 대소문자 문제는 Binder API 문제가 아닌것으로 생각됩니다. 서버에서 대소문자 구별하는지 여부나 ebook의 META-INF/container.xml 파일에 기록된 `.opf`파일 경로를 확인하세요

**Comment by Soarts** [comment]
1. cross browsing
ie, edge, firefox 브라우저에서 ebook - jj.link.html api를 통한 팝업창을 띄울 때, 엉뚱한 경로를 불러서 404에러가 발생하는 케이스가 있습니다.

이 건에 대하여 선행 작업이 가능하신지 문의드립니다!
고객사로부터 웹버전 서비스를 위한 준비를 시작한 참이라, 진작 예상했던 것보다 빨리 필요하게 되었습니다.
선행 작업이 가능한 부분인지, 가능하다면 얼마의 시간이 필요할지 알려주시면 감사하겠습니다.

**Comment by Soarts** [comment]
추가 이슈 문의드립니다.

1. 32bit 크롬에서는 웹버전이 정상 구동되나, 64bit 크롬에서는 정상 구동되지 않음

a. 32bit 크롬에서 실행했을 때
![image](https://cloud.githubusercontent.com/assets/20292746/24992302/a385c1c4-205b-11e7-94bb-7569a7078c24.png)
![image](https://cloud.githubusercontent.com/assets/20292746/24992305/ac48bd8e-205b-11e7-84f3-2f2ad5fbeeec.png)

b. 64bit 크롬에서 실행했을 때
![image](https://cloud.githubusercontent.com/assets/20292746/24992326/c4392096-205b-11e7-8b34-41d681c8f7cd.png)
![20170413_151435_045](https://cloud.githubusercontent.com/assets/20292746/24992352/f97195c2-205b-11e7-89eb-82c9946ce117.jpg)

**Comment by vulcan9** [comment]
크롬 버전 57.0.2987.133 (64-bit)에서  정상적으로 화면이 뜨는것을 확인했습니다.
브라우저에 플러그인 설치가 안되있는 경우 크롬브라우저에서 플래시 활성화 안됨 메세지 표시 후 사용이 가능하도록 안내되고 있습니다.

[Enable for Chrome](https://helpx.adobe.com/flash-player/kb/enabling-flash-player-chrome.html) 내용 참고하시고 다시 테스트 해보시기 바랍니다.

**Comment by vulcan9** [comment]
> 1. cross browsing
ie, edge, firefox 브라우저에서 ebook - jj.link.html api를 통한 팝업창을 띄울 때, 엉뚱한 경로를 불러서 404에러가 발생하는 케이스가 있습니다.

**0.4.239** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by Soarts** [comment]
이슈 해결 확인하였습니다.
