### ISSUE TITLE
파일쓰기 api 적용 관련 문의

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#27]
JIk-ji Binder에서 제공하는 파일쓰기 api를 이용하여
'자료연결' 기능을 개발 중인데, 파일 쓰기를 실행할 때 아래와 같은 에러 발생함.
![-20170109_130350_898](https://cloud.githubusercontent.com/assets/20292746/21757242/503f761c-d66f-11e6-9396-a9356c94cda8.jpg)

뭔가 셋팅을 덜 한 것인가 판단이 드는데, 
작업자 본인은 아무래도 잘 모르겠다고 함.
셋팅을 더 해주어야 할 부분이 있는지 문의드립니다.

오류를 확인할 수 있는 해당 작업 파일은 메시지 주시면 바로 전송해드리겠습니다.

**Comment by vulcan9** [comment]
파일 경로가 정확한지 확인 바랍니다.
```
// * 대상 경로 (파일 원본 위치)
var src = 'C:\\Users\\daum01\\Desktop\\source.jpg';
// * 복사 경로 (파일 복사 위치)
var dest = '/copy.jpg';

jj.io.copy(src, dest, function(err){
    if(err) return alert(err);
    
    // * 실제 복사된 위치 :  ~/binder/user/copy.jpg
    alert('파일 복사 성공!');
});
```

**Comment by Soarts** [comment]
말씀 주신 대로 경로 문제를 해결한 버전을 접수하였습니다.

테스트해보니 아래와 같이 결과가 나왔는데요, PC마다 현상이 다른 것 같아 문의드립니다.

1. Win7 작업자 PC에서는 이상없이 복사 잘 된다고 함.
2. 제 PC(Win10 64bit)에서는 경로가 달라져서 파일 복사가 실행되지 않음
![image](https://cloud.githubusercontent.com/assets/20292746/22189268/ed8a5762-e15e-11e6-8a5d-baceef9094b7.png)

문제가 되는 파일을 별도로 보내드리겠습니다.

**Comment by vulcan9** [comment]
프로그램 캐시 모두 삭제 후 다시 시행해 보시기 바랍니다.
테스트 샘플에서는 Win10에서 정상동작 하는것 같습니다.
기존 저장된 파일 경로를 불러와서 다시 저장하는 로직이 있는것 같은데
파일 경로를 로컬 full path로 저장하는것 같네요
pc가 이동하거나 실행 폴더가 바뀔때 C://로 시작되는 full 경로가 문제가 되겠죠

![20170123_115051](https://cloud.githubusercontent.com/assets/5111882/22189807/4a7b2890-e162-11e6-828b-4b52ace3047f.png)

제 PC에 없는 경로가 저장되어 있네요

**Comment by Soarts** [comment]
새 버전의 자료연결 프로그램을 접수하였고, 테스트 완료하였습니다. 수고하셨습니다
