### ISSUE TITLE
cd에서 Binder를 바로 실행시 오류 발생

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#28]
1. jik-ji Binder(0.1.186)과 콘텐츠를 CD에 담아 cd에서 바로 실행시 에러 발생
![cd](https://cloud.githubusercontent.com/assets/20292746/24860618/6f9948fe-1e30-11e7-9caf-4758e0f99a99.JPG)

2. 이슈 확인을 위하여 파일 제공 가능

**Comment by vulcan9** [comment]
cd에서 바로 실행되지 않습니다.
CD 경로에 파일을 쓸수 없으므로 파일쓰기 과정에서 에러 발생합니다. 
app ID를 동적으로 구분하여 두종류 이상의 app이 멀티 실행되는 부분에서 파일쓰기 에러가 발생한것으로 추측됩니다.

**Comment by vulcan9** [comment]
**Jik-ji-Binder_0.4.236_cdbook_cd 실행.zip** 버전으로 CD 에서 실행 가능하도록 배포 되었습니다.
확인 후 이슈 닫아주시기 바랍니다.

**Comment by Soarts** [comment]
해결되었습니다.
