### ISSUE TITLE
Jik-ji-Binder_web에서 인쇄기능 사용 관련

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#29]
배포된 직지바인더 웹버전에서 ebook 뷰어 기본 기능인 인쇄 기능을 사용 가능했으면 하여 문의드립니다.

1. 테스트 link

- ebook : http://175.126.167.133/~dns/jjb_web_test/viewer/ebook/index.html?contentInformationURL%3D%2F~dns%2Fjjb_web_test%2Fresource%2Febook%2F%26page%3D12%26bookBinding%3Dtrue%26maximize%3Dtrue

2. 설명
 
- 상단 메뉴를 열고 우측 상단에 있는 인쇄 기능을 사용 가능했으면 함.
- 현재는 엑박이 표시되며 동작하지 않고 있음.
- 동일 컨텐츠가 PC용 바인더에서는 전체 인쇄 기능을 사용하고 있음.
- 웹버전에서는 전체 인쇄까지는 필요없고, 현재 페이지 인쇄(웹 기본 프린터)만 제공되면 됨.
- 뷰어에서 확인 결과, 뷰어에서 인쇄할 페이지 이미지의 경로를 알 수 없어 구현할 수 없다고 함.
- 바인더에서 PC용에서처럼 인쇄할 페이지 이미지의 경로를 알려주면, 인쇄 사용이 가능할 듯 함. 
![image](https://cloud.githubusercontent.com/assets/20292746/25076775/dc55f306-235e-11e7-897c-aa8eaa9f9349.png)

**Comment by vulcan9** [comment]
페이지 이미지 목록은 epub 출판할때 `page-info.json` 파일에 기록되어져 있습니다.
`page-info.json` 파일은 ebook 뷰어에서 읽어들입니다.
Binder는 프린트 목록에 대해서는 관여하지 않습니다.

**Comment by Soarts** [comment]
확인하였습니다. 관련 개발자께 문의하겠습니다.
