### ISSUE TITLE
close 이벤트에서 스크립트 오류 후에도 창 종료 되도록..

### ISSUE THREAD

**Issue by vulcan9** [vulcan9/jik-ji-Binder#3]
close 이벤트 핸들러 (사용자 스크립트)에서 스크립트 오류 발생하더라도 창 종료되도록 수정이 필요함

**Comment by vulcan9** [comment]
0.2.65 버전에서 다음 사항이 수정되었습니다.
* uncaught Exception 처리 추가함
* 배포 버전에서 스크립트 오류나는 경우 alert 창으로 알림

사용자가 작성한 스크립트에서 (특히 close 이벤트에 등록된) 오류가 난 경우 창이 닫히지 않는 현상을 해결하기 위해 오류가 발생한 경우 alert으로 오류 내용을 출력하도록 했습니다.
또한 오류났을때 닫히지 않던 문제를 alert 창에 오류 출력후 창이 닫히는 과정을 계속 진행하도록 수정했습니다.

#1 번, #2 번 이슈사항이 이것으로 해결될것 같습니다.
테스트후 댓글로 달아주시면 이 이슈도 close 하겠습니다.

**Comment by Soarts** [comment]
flash에서 테스트결과 콘텐츠 스크립트 오류가 확인되어 공유드립니다.
![2](https://cloud.githubusercontent.com/assets/20292746/17239612/5fa41f68-55a0-11e6-9a09-2a7a5a80224c.JPG)

**Comment by vulcan9** [comment]
오류 내용이 alert 창으로 출력되는건 모두 컨텐츠쪽에서 사용자가 작성한 스크립트 오류입니다.

화면에서 에러내용은 close 이벤트에서 발생한 오류이고, resource/contents/main.html에 60번째 라인에서 jj 속성을 찾지 못하네요
참고로 창은 닫히더라도 close 이벤트에 작성한 내용은 오류로인해 실행되지 않습니다.

이 이슈는 닫겠습니다.
