### ISSUE TITLE
cd에서 Binder를 바로 실행시 로딩이미지 처리 관련

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#30]
1. cd에서 Binder를 바로 실행시,
exe 실행이 완료되며 응용프로그램 창이 표시되나,
바탕이 하얗게 아무것도 보여지지 않는 상태로 20초 이상 지속되어
로딩 중이라는 것에 대한 사용자 인지가 어려운 상황.

2. 사용자로 하여금 로딩 중이라는 인지를 할 수 있도록 로딩 이미지를 표시하거나, 로딩 자체를 줄일 수 있는 지 검토 필요

**Comment by vulcan9** [comment]
cd 에서 첫 실행한 경우 cd에 포함된 webkit 브라우져를 실행하기 위한 전단계로 로컬 드라이브에 여러가지 파일들 및 데이터가 생성되고 설정되는 과정을 거치게 됩니다.
이 과정은 크롬 브라우져가 PC에 설치된 후 첫 구동할때와 같습니다.
PC와는 달리 CD에서 데이터를 읽어들여야 하므로 첫 구동시 시간이 좀더 지체되는 현상으로 나타나는 것으로 보입니다.
splash 화면을 띄울수 있는지 검토중입니다.

**Comment by vulcan9** [comment]
splash 이미지 사용하도록 기능 추가 되었습니다.
CD에서 중복실행 체크 기능 추가되었습니다.
**0.4.257** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by Soarts** [comment]
window.jj.opener().closeSplash(window);

위 코드를 index.html에 추가한 뒤에, 
우선 실행은 정상적으로 되나,

ebook viewer에서 홈 버튼을 통하여 다시 index.html로 돌아올 때 이러한 에러가 표시됩니다.
![_](https://cloud.githubusercontent.com/assets/20292746/25513971/2cf67fe8-2c14-11e7-889e-2b002c8d6b84.png)

에러메시지가 뜬 이후에는 정상적으로 index.html이 실행되기는 합니다.
이러한 에러를 표시되지 않도록 하려면 추가 코드 작업이 필요한지 확인 요청드립니다.

**Comment by vulcan9** [comment]
```
window.jj.opener().closeSplash(window);
```
위 코드를 다음 코드로 수정하세요
```
if(window.jj){
    var opener = window.jj.opener();
    if(opener && opener.closeSplash) opener.closeSplash(window);
}
```

**Comment by Soarts** [comment]
해결되었습니다.
