### ISSUE TITLE
cd로 바로실행 가능한 Jik-ji-Binder 구조 3종 추가 요청

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#31]
app-id 동적생성 기능이 제거된 Jik-ji-Binder 요청드립니다.
- 용도 : 미래엔 전자저작물CD(중학교 과학) 수정사항 반영

- 고정 app id : scic_001, scic_002, scic_003

**Comment by vulcan9** [comment]
**0.4.243** 버전(이상)에서 처리(구현) 되었습니다.
