### ISSUE TITLE
cd로 바로 실행이 가능한 Jik-ji-Binder 고객사 수정 의견

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#32]
이 요청사항은 최근 배포된 scic01, scic02, scic03 구조에 각각 반영 부탁드립니다.

1. 현재 콘텐츠가 실행되면 창이 "전체화면"으로 표시되어 작업 표시줄까지 가리도록 되어있는데,
 - "최대화"로 표시되도록 수정 요망
 - 현재 이것 때문인지는 알 수 없으나 창이 리사이징이 되지 않습니다. 리사이징이 가능해야 할 듯 합니다.

2. 아래 작업표시줄에 표시되는 splash의 문자 변경 가능여부, 가능하다면 수정 요망
![image](https://cloud.githubusercontent.com/assets/20292746/25322713/84b56104-28f4-11e7-9077-42c1f86bfc1c.png)
  - 문자 변경 : "splash" -> "로딩 중" (영문만 가능하다면 "Loading")
  - 앱 아이디 변경 : 2015TNN_70N_CD1,2015TNN_70N_CD2, 2015TNN_70N_CD3

**Comment by vulcan9** [comment]
1. "최대화" 기능 관련 문제는 window 창의 최대화 버튼 기능을 사용합니다. 다른 브라우저를 열어 최대화 버튼을 눌러 같은 현상이 있는지 확인 바랍니다. (개인 PC의 동작 차이일 수 있습니다.)

2. splash의 문자를 변경기능을 추가하였습니다.
- "로딩중입니다"로 기본 표기됩니다. (bin/package.json 의 name 항목)
- 컨텐츠 창에서도 해당 부분의 표시 글자를 바꾸려면 app/package.json 파일의 name 항목을 수정하시면 됩니다.
```
package.json 파일의 name 항목은 폴더 생성할때 명명 규칙이 적용됩니다.
따라서 특수문자나 dot(.) 등의 문자는 허용되지 않습니다.
```

**0.4.257** 버전(이상)에서 처리(구현) 되었습니다.
확인 후 이슈 닫아주시기 바랍니다.
