### ISSUE TITLE
Jik-ji-Binder web 콘텐츠를 IE에서 실행했을 때 jj.link.html로 띄워진 새창의 리사이징이 안되는 현상

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#34]
1. Chrome에서는 문제 없음

2. IE에서 ebook 버튼(jj.link.html)을 클릭시 뜨는 새창을 리사이징 할 수 없음

[URL]
http://175.126.167.133/~dns/jjb_web_test/viewer/ebook/index.html?contentInformationURL=/~dns/jjb_web_test/resource/ebook/&page=12&bookBinding=true&maximize=true

![image](https://cloud.githubusercontent.com/assets/20292746/25978325/850eca76-36fc-11e7-88d8-c63c87e53fc5.png)

**Comment by vulcan9** [comment]
IE11에서 팝업창 resize 기능에 issue가 있는것으로 압니다만,
좀더 조사한 후 확실한 내용을 알려드리겠습니다.

**Comment by vulcan9** [comment]
웹 버전의 경우 Binder API의 기능적인 제약이 있을 수 있습니다. 
(Binder API 도움말에 `not web` 으로 표기됨)
web 버전에서 link API의 경우 다음 제약이 있습니다.

![20180412_103629](https://user-images.githubusercontent.com/5111882/38651664-6378758a-3e3d-11e8-8f5a-daf8c91084a9.png)

web 버전에서 Popup 창을 띄우는 경우 `IE11 브라우져`는 윈도우 resize 정책이 다른 브라우져와 조금 다릅니다. 창 크기 조절 옵션을 주지 않았을때 기본동작으로 창크기 조절을 못하도록 동작하네요.
- 이 부분은 Binder API에서 기본동작이 동일하게 동작(resize 가능)하도록 수정해야할 것 같습니다.
- 아울러 link API에 resize 옵션을 추가해야 할것 같습니다.

**Comment by vulcan9** [comment]
**0.4.239.web** 버전(이상)에서 처리(구현) 되었습니다.
