### ISSUE TITLE
cd 실행 가능하게 하는 구조(app-id 고정) 요청

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#35]
app-id 동적 생성 기능을 제거한 8개의 구조를 요청드립니다.
아래는 지정될 app-id입니다.

01. 2015TEE_70L_CD1 / 2015TEE_70L_CD2 / 2015TEE_70L_CD3
02. TB2015TC2EE_70JS_CD1 / TB2015TC2EE_70JS_CD2 / TB2015TC2EE_70JS_CD3
03. 2015SJP_00P_CD1
04. 2015SCH_00S_CD1

**Comment by vulcan9** [comment]
8개 아이디로 빌드 후 보내드렸습니다. 
확인후 이슈 닫아주세요.
