### ISSUE TITLE
Jik-ji-Binder_0.4.186과 Jik-ji-Binder_0.4.257의 플래시 재생의 상이점 확인 요청

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#36]
작년에 배포되었던 Jik-ji-Binder_0.4.186를 통하여 플래시가 재생되는 것과
최근 배포된 Jik-ji-Binder_0.4.257를 통하여 동일한 플래시가 재생되는 것이 다소 다르게 보여지는 현상이 접수되었습니다.

resource는 동일하고 구조만 다른 형태인데,
Jik-ji-Binder_0.4.186는 이 콘텐츠(플래시) 재생시 정상적으로 부드럽게 재생이 되지만
Jik-ji-Binder_0.4.257는 프레임드랍 현상이 일어납니다.(시각적으로  끊기면서 재생됨)

플래시 뷰어의 차이가 있는 것인지, 기존처럼 프레임드랍이 일어나지 않도록 할 수 있는지 문의드립니다.

**Comment by vulcan9** [comment]
gpu 랜더링을 사용하지 않고 cpu 랜더링을 사용하도록 설정되어있어 부드러운 화면으로 재생되지 않은것 같습니다.
package.json에서 다음 옵션이 설정되어 있다면 이를 삭제해주면 됩니다.
* --disable-gpu
* --force-cpu-draw

**Comment by Soarts** [comment]
해결 되었습니다.
