### ISSUE TITLE
cd 실행 가능하게 하는 구조(app-id 고정) 요청(17.8.9)

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#37]
cd 실행 가능하게 하는 구조(app-id 고정) 요청 
app-id 동적 생성 기능을 제거한 총 19개의 구조를 요청드립니다.
아래는 지정될 app-id입니다.

1. 중등 과학
2015TNN_80N_CD1
2015TNN_80N_CD2
2015TNN_80N_CD3

2. 중등 영어 A팀
2015TEE_80L_CD1
2015TEE_80L_CD2
2015TEE_80L_CD3

3. 중등 영어 B팀
TB2015TC2EE_80J_CD1
TB2015TC2EE_80J_CD2
TB2015TC2EE_80J_CD3

4. 중등 국어A팀
EB2015TC2KK_71N_CD

5. 중등 국어B팀
EB2015TC2KK_71P_CD

6. 고등 국어 A팀
EB2015TC3KK_00P_CD

7. 고등 국어 B팀
EB2015TC3KK_00L_CD

8. 중등 생활일본어
EB2015TC2JP_70_CD

9. 중등 생활중국어
EB2015TC2CH_70_CD

10. 고등 중국어1
EB2015TC3CH_10_CD

11. 고등 일본어1
EB2015TC3JP_10_CD

12. 고등 통합 과학
EB2015TC3Etc_037_00_CD

13. 고등 통합과학실험
EB2015TC3Etc_038_00_CD

**Comment by vulcan9** [comment]
해당 파일 전달 되었습니다.
