### ISSUE TITLE
app-id가 고정된 구조에서 ebook -> main 이동시 오류

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#38]
1. app-id가 고정된 구조(html 콘텐츠)에서 index.html에 closeSplash 코드 추가
<script>
window.jj.opener().closeSplash(window);
</script>

2. main 열때 Splash 창이 잘 닫히고 정상적으로 열림.

3. main -> ebook 이동후, ebook viewer의 home 버튼 클릭하여 main으로 이동할 때 오류 발생
![image](https://user-images.githubusercontent.com/20292746/29852394-d2da7d30-8d74-11e7-8b9c-fe6c16ecf5cf.png)

 <오류 얼럿>
![image](https://user-images.githubusercontent.com/20292746/29852385-ccf2c9f4-8d74-11e7-8d82-0cf42bde8816.png)
![image](https://user-images.githubusercontent.com/20292746/29852388-ce99695c-8d74-11e7-8a12-6cff550191b2.png)

**Comment by vulcan9** [comment]
window.jj.opener() 가  있는지 먼저 체크하는 로직을 추가하세요
```
if(window.jj){
    var opener = window.jj.opener();
    if(opener) opener.closeSplash(window)
}
```

**Comment by Soarts** [comment]
해당 내용을 index.html에 추가하면 되는지요?
현재 해당 index.html의 전문인데, 어떻게 추가하면 되는지 가이드를 주시면 감사하겠습니다.

<!DOCTYPE html>
<html lang="ko">
    <head>
        <title>중등 국어 1-1_박영목</title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <link rel="stylesheet" href="./include/smartIntro/css/intro.css">
        <script src="./include/smartIntro/js/intro.js"></script>
    </head>
    <body>
        <div id="mainBgContainer"></div>
        <div id="mainContainer"></div>
        <div id="loadingContainer">
            <div class="loadingIconAnimation"></div>
        </div>
        <script>
        window.jj.opener().closeSplash(window);
        </script>
    </body>
</html>

**Comment by vulcan9** [comment]
```
<script>
if(window.jj && window.jj.opener()){
    window.jj.opener().closeSplash(window)
}
</script>
```
