### ISSUE TITLE
jik-ji-Binder 웹버전에 컨텐츠 적용 테스트 중 문의

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#39]
최근 한 출판사의 CD용 콘텐츠를 jj binder 웹버전에 적용하여 테스트를 진행하고 있습니다.

해당 데이터를 서버에 업로드하고 브라우저를 통하여 해당 url로 접근해보았는데,

ebook viewer와 섬네일까지만 로드되고 책 내용이 로드되지 않는 현상이 있습니다.

해당 ebook은 jik-ji 저작도구로 작성된 것입니다.

혹시 어떤 부분을 점검해봐야 하는지 도움주시면 감사하겠습니다.

제가 아는 방법으로는 이게 분명히 맞는데 잘 안되네요.

http://175.126.167.133/~dns/ksw/jjb_web_0904/viewer/ebook/index.html?contentInformationURL=/~dns/ksw/jjb_web_0904/resource/ebook/&bookBinding=true

![image](https://user-images.githubusercontent.com/20292746/30041270-a0da082e-9223-11e7-8496-588abd63e0b0.png)

**Comment by vulcan9** [comment]
원인 : 잘못된 html 헤더 설정
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
```

xml 헤더부분을 빼주어야 서버에서 정상 작동합니다.

**Comment by Soarts** [comment]
해결되었습니다.
