### ISSUE TITLE
플래시 녹음기능 / 녹음파일 저장경로가 다른 문제

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#4]
저장경로가 달라서 재생이 안됨.

**Comment by spvog** [comment]
>> 기존 버전(일본어)의 저장 경로
C:\Users\Administrator\AppData\Local\Temp\micrec1.mp3
>> jik-ji-Binder 저장 경로
C:\Users\Administrator\AppData\Local\Temp\vulcan.jikji.binder\record\

1. 기존 방식과 다름(일본어는 1개의 mp3를 생성 후 덮어씌우기 및 재생 -  jik-ji-Binder는 녹음을 할 때마다 mp3가 새로 생성됨)
2. 녹음 및 정지는 되는데 재생이 안됨.
3. 플래시에서 url을 수정하는 방법을 모르겠슴.

**Comment by vulcan9** [comment]
녹음 mp3가 계속 덮어쓰기 되도 되는겁니까?
일정 잡아서 샘플만들어 보겠습니다.

**Comment by Soarts** [comment]
mp3 덮어쓰면 안됩니다. 녹음할 때마다 새로운 mp3가 생성되어야 합니다.

**Comment by vulcan9** [comment]
저장 경로 및 파일 이름을 지정하여 녹음하는 방법은 지금도 지원되고 있습니다. (jj.record API 참고)
다만 플래시에서는 녹음이 끝났을때 리턴값을 받는 과정이 복접할수있어 예제를 제공할 예정입니다.

**Comment by vulcan9** [comment]
**0.2.68** 버전(이상)에서 처리(구현) 되었습니다.
