### ISSUE TITLE
jik-ji 0.1.693에서 작업한 jik을 0.3.0에서 재출판후 jik-ji Binder로 구동시 액션이 동작하지 않는 현상

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#40]
jik-ji 0.1.693에서 작업한 jik을 0.3.0에서 재출판후 jik-ji Binder로 구동시 액션이 동작하지 않는 현상

천재교육으로부터 제공된 jik과 cd구조를 함께 확인하였을 때
ebook에서 jj binder api를 사용한 액션들이 동작하지 않습니다.

테스트 파일은 별도로 발송드리겠습니다.

**Comment by vulcan9** [comment]
원인 : 
> 1. (0.3.0 이전 버전에서는) 스크립트로 작성된 코드중에 이벤트를 직접 제어하는 코드에서 이벤트 bubbling 현상으로 같은 이벤트가 여러번 실행되는 현상이 발생했었음.
> 2. 이 현상을 해결하기 위해 event.target 속성을 조사하여 선별적으로 이벤트 실행을 필터링함.
> 3. 경우에 따라 마우스 동작으로 trigger되는 이벤트가 전달되지 않는 현상이 발생되어 실행되지 않음

해결 : 
> 1. 이벤트 버블링을 막는 방법으로 event.target 속성을 조사하는 것은 상황에 따라 오작동할 소지가 있으므로 사용하지 않는다.
> 2. 이벤트를 trigger 할때 `trigger` 메서드 대신 `triggerHandler` 메서드를 사용 한다.
> 3.  `trigger` 메서드와 `triggerHandler` 메서드 차이점은 다음 링크에서 참고할것.
[(triggerHandler 메서드)](http://api.jquery.com/triggerHandler/#triggerHandler-eventType-extraParameters)

**Comment by vulcan9** [comment]
이 문제는 jik-ji 저작툴 관련 사항입니다.
**Jik-ji 0.3.5** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by Soarts** [comment]
확인하였습니다. 감사합니다.
