### ISSUE TITLE
플래시 콘텐츠를 jjb 환경에서 사용할 때 Fullscreen api 관련 확인 요청 사항

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#43]
![image](https://user-images.githubusercontent.com/20292746/31802645-4e5c9ef6-b58a-11e7-988c-babba998115e.png)

플래시 콘텐츠에서 풀스크린창을 호출하는 api를 사용할 때 토글이 동작하지 않는 것 같다는 제보가 왔습니다.
풀스크린은 되는데 esc로 복원되지 않는게 문제라고 하네요. (반응 없음)

저희가 제공한 api에 문제가 없는지 확인 요청 드립니다.

**Comment by vulcan9** [comment]
api는 문제 없는것 같습니다.
컨텐츠의 flash 또는 Html에서 keyboard 관련 처리부분이 있는지 확인해보는게 좋겠습니다.
