### ISSUE TITLE
특수교과서용 전자저작물 CD에서 콘텐츠 에러 얼럿 숨기기 작업 요청

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#45]
특수교과서용 전자저작물 CD에서 콘텐츠 에러 얼럿 숨기기 요청드립니다.

**Comment by vulcan9** [comment]
**Jik-ji-Binder_0.4.261_cdbook_cd_appid** 버전(이상)에서 처리(구현) 되었습니다.
