### ISSUE TITLE
폴더를 zip파일로 압축후 다운로드 api 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji-Binder#48]
다중선택(전체선택)하여 폴더를 다운로드하는 경우에는 zip으로 압축하여 내려받을 수 있도록
api 추가 개발 검토가 필요합니다.

**Comment by vulcan9** [comment]
zip 압축 인터페이스 제작에 2~3일 소요 될것으로 예상됩니다.
개발 시작 시점 및 배포 일정은 협의가 필요합니다.

**Comment by vulcan9** [comment]
**0.4.272** 버전(이상)에서 처리(구현) 되었습니다.
* 압축 API 추가 (`jj.native.zip`)
* 파일 압축 다운로드 기능 추가 (`jj.native.zipDownload`)
