### ISSUE TITLE
스크립트 직접 입력시 사라지는 현상

### ISSUE THREAD

**Issue by hi763** [vulcan9/jik-ji-Binder#54]
1. 1page에 이벤트로 직접 스크립트 입력
 event-document- on load에서  add action - 스크립트 작성
 완료 후 

2. 2page(다른 페이지)에서 위와 동일한 순서로 스크립트 작성

경우1) 
=> 2page에 스크립트 추가 안됨
=> 1pgae에 기존 스크립트가 아닌 2page에 등록된 스크립트로 변경

경우2) 
=> 2page에 스크립트 추가 안됨
=> 1pgae에 기존 스크립트와 함께 2page에서 등록한 스크립트가 함께 보여짐

**Comment by vulcan9** [comment]
Jik-ji Editor 이슈로 게시물 이동했습니다.
[스크립트 입력이 되지 않는 현상 #131](https://github.com/vulcan9/jik-ji/issues/131)
