### ISSUE TITLE
jik-ji-Binder에서 통권 콘텐츠 열기 관련

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#6]
마이너스 페이지 구현 가능 여부 테스트 과정에서 나온 이슈입니다.

현재 주어진 jik-ji-Binder 교사용CD 구조에서 
통권 콘텐츠를 적용시, 아래와 같은 스크립트 오류가 표시되고 콘텐츠(epub 뷰어)가 실행되지 않는 현상이 있습니다.

[1 : 에러메시지1]
![1](https://cloud.githubusercontent.com/assets/20292746/18622798/697a0898-7e6f-11e6-9e55-1d1f1737df0b.JPG)
[1-2 : 에러메시지1 - 이어서]
![1-2](https://cloud.githubusercontent.com/assets/20292746/18622800/71631fe0-7e6f-11e6-94fa-1ec78503c17c.JPG)
[2 : 에러메시지2]
![2](https://cloud.githubusercontent.com/assets/20292746/18622802/778886d0-7e6f-11e6-89df-ac8a31f805ea.JPG)

이 현상과 관련 내용은 공유된 상태이며,  
1. jik-ji-Binder에서 ebook으로 링크를 거는 api와 관련된 사항을 좀더 알아야 될 것 같다.
2. 로그를 봐야할 것 같다
라는 의견을 남겨주신 상태입니다.

테스트 방법은 아래와 같습니다.
1. 콘텐츠 구조에 들어가있는 epub을 가지고, 통권 콘텐츠를 만든다.(사이버학습 패키저)
2. 통권콘텐츠에 포함된 epub과 통권에 대한 xml(digitaltextbook.xml)을 교사용CD구조에 맞추어 넣는다.
3. launcher.exe를 실행한다.

테스트에 사용된 파일은 고용량으로 여기에는 첨부하지 못하고, 필요하실 때 말씀 하시면 별도로 전송드릴 수 있도록 하겠습니다.

**Comment by vulcan9** [comment]
digitaltextbook.xml 을 못읽어 들여서 뷰어쪽에서 스크립트 에러가 발생한것으로 예상됩니다.
xml이 resource폴더 밖에 있던지 아니면 접근할수 없는 권한 밖에 위치에 있던지 하는 이유로 뷰어에서 읽기 실패했을 가능성이 있을것 같습니다.
자세한 내용은 샘플을 주시면 파악이 될거 같네요

**Comment by vulcan9** [comment]
통권 및 분권 구분하여 처리되도록 뷰어와 함께 업데이트 되었습니다.
**0.3.32** 버전(이상)에서 처리(구현) 되었습니다.
