### ISSUE TITLE
터치 이벤트 추가 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jik-ji-Binder#62]
**현상**
컴포넌트 개발 중 비디오/오디오 컨트롤러의 프로그레스 바 및 음량 조절 바를 모바일 환경에서 드래그로 조절이 되지 않는 것을 발견

**수정 요청**
드래그 api에 터치 이벤트를 추가 필요

**Comment by vulcan9** [comment]
> jik.editor 이슈로 이전합니다. [터치 이벤트 추가 요청 #188](https://github.com/vulcan9/jikji.editor/issues/188)
