### ISSUE TITLE
file copy 기능

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jik-ji-Binder#9]
jik-ji-Binder를 활용하여
사용자 로컬 file이 원하는 경로(교사용CD구조/app/user/reflink)로
file copy 하는 기능 필요

**Comment by vulcan9** [comment]
일단 다음 기준으로 API 개발 합니다.

1. copy 기능을 제공하되 복사 결과 폴더가 user 폴더로 고정합니다.
2. user 폴더 이하 경로부터 사용자가 지정한 경로에 복사될 수 있도록 합니다. (없는 폴더는 자동 생성)
특정 폴더를 미리 생성해 주어야 한다든지하는 작업은 Binder에서 하지 않습니다. 
3. 한번에 하나의 파일만 복사합니다. 폴더단위 또는 여러 파일을 한번에 복사하는 기능은 일단 지원하지 않는것으로 합니다.
4. user 폴더안에서 파일 접근은 자유롭기 때문에 Binder에서 파일 중복 체크같은 기능을 지원하지 않습니다. API 사용자가 복사할 이름(또는 경로)을 아이디로 전달한다든지 하여 파일 중복을 회피하도록 합니다.
5. 복사된 리소스를 사용하기 위해 user 폴더에 접근하는 방식을 공개합니다.
6. 실행 파일은 복사되지 않도록 합니다.

**Comment by vulcan9** [comment]
**0.3.43** 버전(이상)에서 처리(구현) 되었습니다.
